//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorWPFi18n.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorWPFi18n.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string _virtual {
            get {
                return ResourceManager.GetString("virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        public static string disco {
            get {
                return ResourceManager.GetString("disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escritura.
        /// </summary>
        public static string escritura {
            get {
                return ResourceManager.GetString("escritura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabricante.
        /// </summary>
        public static string fabricante {
            get {
                return ResourceManager.GetString("fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Física.
        /// </summary>
        public static string fisica {
            get {
                return ResourceManager.GetString("fisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string iniciar {
            get {
                return ResourceManager.GetString("iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectura.
        /// </summary>
        public static string lectura {
            get {
                return ResourceManager.GetString("lectura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria.
        /// </summary>
        public static string memoria {
            get {
                return ResourceManager.GetString("memoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenador.
        /// </summary>
        public static string ordenador {
            get {
                return ResourceManager.GetString("ordenador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes enviados.
        /// </summary>
        public static string paquetes_enviados {
            get {
                return ResourceManager.GetString("paquetes-enviados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes recibidos.
        /// </summary>
        public static string paquetes_recibidos {
            get {
                return ResourceManager.GetString("paquetes-recibidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizar.
        /// </summary>
        public static string personalizar {
            get {
                return ResourceManager.GetString("personalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
    }
}
